[package]
name = "rusty-trmnl-display"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
embedded-graphics = "0.8.1"
embedded-graphics-simulator = "0.7.0"
tinybmp = "0.6.0"
tokio = { version = "1", features = ["full"] }
